name: lpstudent
description: A new Flutter project.
# https://appsenjoy.com/download/a1bb4dab9c3e21191af68389cb526142.html
# https://appsenjoy.com/delete/684a2b0fa8c72fb9e1697d6a06ebcbd1.html
version: 1.0.0+10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  expandable: ^3.0.1
  
  shared_preferences: any
  flutter_calendar_carousel: any
  qr_flutter: any
  path_provider: ^1.6.1
  
  table_calendar: ^2.2.2
  intl: any
  outline_material_icons: any
  firebase_core: ^0.4.4+2

  rxdart: 0.20.0
  cloud_firestore: 0.13.4

  flutter_signin_button: 1.0.0

  #Codemagic tutorial 
  firebase_auth: 0.15.4
  google_sign_in: ^3.2.4

  back_button_interceptor: any
  url_launcher: 5.4.2
  percent_indicator: "^2.1.1"
  flutter_custom_dialog: ^1.0.19
  flutter_local_notifications: 1.4.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.6.1"

module:
  androidX: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/Day_Specific/General1.jpeg
    - assets/images/Day_Specific/General2.jpg
    - assets/images/Day_Specific/General3.jpg
    - assets/images/Day_Specific/General4.jpg
    - assets/images/Day_Specific/General5.png

    - assets/images/Day_Specific/Band1.jpg
    - assets/images/Day_Specific/Band2.jpg
    - assets/images/Day_Specific/Band3.jpg
    - assets/images/Day_Specific/Band4.jpg

    - assets/images/Day_Specific/Basketball1.jpg
    - assets/images/Day_Specific/Basketball2.jpg

    - assets/images/Day_Specific/Classroom1.jpg
    - assets/images/Day_Specific/Classroom2.jpg

    - assets/images/Day_Specific/Football1.jpg
    - assets/images/Day_Specific/Football2.jpg
    - assets/images/Day_Specific/Football3.jpg
    - assets/images/Day_Specific/Football4.jpg

    - assets/images/Day_Specific/Soccer1.jpg
    - assets/images/Day_Specific/Soccer2.jpg

    - assets/images/Day_Specific/Track1.jpg
    - assets/images/Day_Specific/Track2.jpg
    - assets/images/Day_Specific/Track3.jpg

    - assets/images/Day_Specific/Volleyball1.jpg
    - assets/images/Day_Specific/Volleyball2.jpg
    - assets/images/Day_Specific/Volleyball3.jpg

    - assets/images/Day_Specific/Auditorium1.jpg

    - assets/images/Day_Specific/Snow1.jpg

    - assets/images/LP_Student/LP_Student.png
    - assets/images/LP_Student/LP_Student_Shadow.png

    - assets/images/Services/PowerSchool.jpg
    - assets/images/LP/LP_Original.png
    - assets/images/Services/Efunds.jpg
    - assets/images/Services/Outlook.png
    - assets/images/Services/Classroom.png

    - assets/handbook.pdf
  

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/roboto/Roboto-Regular.ttf


  
flutter_icons:
  image_path: "assets/appicon.png" 
  android: true
  ios: true