name: lpstudent
description: A new Flutter project.

version: 1.0.0+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  expandable: ^3.0.1
  google_sign_in: ^3.2.4
  shared_preferences: any
  flutter_calendar_carousel: any
  qr_flutter: any
  path_provider: ^1.6.1
  firebase_auth: 0.15.4
  table_calendar: ^2.2.2
  intl: any
  outline_material_icons: any
  firebase_core: 0.4.4
  firebase_analytics: ^1.0.4
  rxdart: 0.20.0
  cloud_firestore: 0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

module:

  androidX: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/generalDay/gen.jpeg
    - assets/images/generalDay/gen2.jpg
    - assets/images/generalDay/gen3.jpg
    - assets/images/snowDay/snow.jpg
    - assets/images/logo2.png
    - assets/images/appicon.png
